USE Empresa;
--EJERCICIO 1
SELECT DESCRIP
FROM PROYECTOS
WHERE DESCRIP = (SELECT FECHA FROM TRABAJOS
WHERE FECHA BETWEEN DAY(11)&MONTH(09)& YEAR(2014) AND DAY(15) & MONTH(09)&YEAR(2014))
GROUP BY DESCRIP;

--EJERCICIO 2
SELECT EMPLEADOS.NOMBRE
FROM EMPLEADOS INNER JOIN TRABAJOS
ON EMPLEADOS.CODE= TRABAJOS.CODE
INNER JOIN MAQUINAS
ON TRABAJOS.CODM=MAQUINAS.CODM
INNER JOIN PROYECTOS
ON TRABAJOS.CODP=PROYECTOS.CODP
WHERE MAQUINAS.NOMBRE LIKE 'Volquete'
GROUP BY EMPLEADOS.NOMBRE, PROYECTOS.LOCALIDAD
HAVING PROYECTOS.LOCALIDAD LIKE 'Arganda';

--EJERCICIO 3
SELECT * 
FROM EMPLEADOS INNER JOIN TRABAJOS 
ON EMPLEADOS.CODE=TRABAJOS.CODE
WHERE TRABAJOS.TIEMPO IS NULL AND CODP IS NOT NULL;

--EJERCICIO 4
SELECT MAQUINAS.NOMBRE, MAQUINAS.PRECIOHORA
FROM MAQUINAS
WHERE MAQUINAS.PRECIOHORA LIKE (SELECT MAX(MAQUINAS.PRECIOHORA) FROM MAQUINAS);

--EJERCICIO 5
SELECT EMPLEADOS.NOMBRE, COUNT(TRABAJOS.CODP)
FROM EMPLEADOS INNER JOIN TRABAJOS
ON EMPLEADOS.CODE=TRABAJOS.CODE
GROUP BY EMPLEADOS.NOMBRE;

--EJERCICIO 6
SELECT LOCALIDAD, COUNT(LOCALIDAD)
FROM EMPLEADOS
GROUP BY LOCALIDAD;

--EJERCICIO 7
SELECT PROYECTOS.CLIENTE, SUM(TRABAJOS.TIEMPO)
FROM PROYECTOS INNER JOIN TRABAJOS
ON PROYECTOS.CODP=TRABAJOS.CODP
GROUP BY PROYECTOS.CLIENTE

--EJERCICIO 8
SELECT EMPLEADOS.NOMBRE, EMPLEADOS.LOCALIDAD AS LOCALIDAD_EMPLEADO, PROYECTOS.LOCALIDAD AS LOCALIDAD_PROYECTO
FROM EMPLEADOS INNER JOIN TRABAJOS
ON  EMPLEADOS.CODE=TRABAJOS.CODE
INNER JOIN PROYECTOS
ON TRABAJOS.CODP=PROYECTOS.CODP
WHERE EMPLEADOS.NOMBRE LIKE '%Pérez' AND EMPLEADOS.LOCALIDAD <> PROYECTOS.LOCALIDAD;

--EJERCICIO 9
SELECT MAX(MAQUINAS.PRECIOHORA*TRABAJOS.TIEMPO), DESCRIP
FROM MAQUINAS INNER JOIN TRABAJOS
ON MAQUINAS.CODM=TRABAJOS.CODM INNER JOIN PROYECTOS 
ON PROYECTOS.CODP=TRABAJOS.CODP
GROUP BY DESCRIP;

--EJERCICIO 10
SELECT EMPLEADOS.NOMBRE, PROYECTOS.CLIENTE, PROYECTOS.LOCALIDAD
FROM EMPLEADOS INNER JOIN TRABAJOS
ON EMPLEADOS.CODE=TRABAJOS.CODE
INNER JOIN PROYECTOS
ON PROYECTOS.CODP=TRABAJOS.CODP
INNER JOIN MAQUINAS
ON MAQUINAS.CODM=TRABAJOS.CODM
WHERE MAQUINAS.PRECIOHORA LIKE (SELECT MAX(MAQUINAS.PRECIOHORA) FROM MAQUINAS);
