USE [PRUEBA.DB]
--EJERCICIO 1
CREATE VIEW CONSERJES AS 
SELECT personal.apellidos, centros.nombre
FROM personal inner join centros
on personal.apellidos =centros.cod_centro
WHERE personal.funcion='CONSERJE';

SELECT * FROM CONSERJES

--EJERCICIO 2
ALTER TABLE PROFESORES
ADD COD_ASIG VARCHAR(2);

--EJERCICIO 3
CREATE TABLE TASIG(
COD_ASIG INT NOT NULL, 
NOM_ASIG VARCHAR(20)
);

--EJERCICIO 4
ALTER TABLE TASIG
ADD CONSTRAINT PK_CODASIG PRIMARY KEY (COD_ASIG);

--EJERCICIO 5
ALTER TABLE PROFESORES
ADD CONSTRAINT FK_CODASIG FOREIGN KEY (COD_ASIG)
REFERENCES TASIG ON DELETE CASCADE;

--EJERCICIO 6
CREATE VIEW CENTROSPROFESORES AS
SELECT profesores.apellidos, profesores.especialidad, centros.nombre
FROM profesores INNER JOIN centros
ON profesores.cod_centro=centros.cod_centro;

SELECT * FROM CENTROSPROFESORES

--EJERCICIO 7
CREATE VIEW PROFESORESCENTROS AS
SELECT centros.nombre ,COUNT(profesores.dni) AS CONTADOR
FROM centros INNER JOIN profesores
ON centros.cod_centro=profesores.cod_centro
GROUP BY centros.nombre;

SELECT * FROM PROFESORESCENTROS;

--EJERCICIO 8
CREATE TABLE AUDITORIA(
FECHA_CREACION DATE,
HORA TIME,
TEXTO VARCHAR 
)
DBCC USEROPTIONS