CREATE DATABASE TEST;
GO
USE TEST;
CREATE TABLE TB1(COD INT PRIMARY KEY, NUM1 INT)
SET XACT_ABORT OFF
BEGIN TRAN
INSERT INTO TB1 VALUES(1,2)
INSERT INTO TB1 VALUES(2,3)
INSERT INTO TB1 VALUES (1,3)
COMMIT TRAN 
SELECT * FROM TB1;