USE [PRUEBA.DB]
--Añadir dos columnas: SEXO  (no admite valores nulos) (CHAR(1)) e IMPORTE (TINYINT).
ALTER TABLE CONDICIONES
ADD SEXO CHAR(1) NOT NULL,
IMPORTE TINYINT;

--Modifica la tabla sexo
ALTER TABLE CONDICIONES
ALTER COLUMN SEXO VARCHAR(12);
ALTER TABLE CONDICIONES ALTER COLUMN IMPORTE INT;

ALTER TABLE CONDICIONES ADD CONSTRAINT CK_SEXO;

ALTER TABLE CONDICIONES DROP CONSTRAINT CK_SEXO;
ALTER TABLE CONDICIONES DROP COLUMN SEXO, IMPORTE;
ALTER TABLE CONDICIONES DROP PK_CONDICIONES_DNI; 

