--DEFINIR EL CODIGO PEDIDO, EL NUMERO DE LINEAS DE CADA PEDIDO Y EL MAX Y EL MIN DE SUS LINEAS DE PEDIDO
CREATE VIEW VISTA4 AS 
SELECT CodigoPedido, COUNT(NumeroLinea) AS CONTADOR, MIN(PrecioUnidad*Cantidad) AS MINIMO, MAX(PrecioUnidad*Cantidad) AS MAXIMO
FROM DetallePedidos
GROUP BY DetallePedidos.CodigoPedido;

SELECT * FROM VISTA4;