use Jardineria;
SELECT ESTADO, 'ESTADO'=
CASE 
WHEN FechaEntrega IS NULL THEN 'NO ENTREGADO'
ELSE 'ENTREGADO'
END
FROM Pedidos
--EJERCICIO 2
SELECT CODIGOPEDIDO,
ISNULL(CAST(FECHAENTREGA AS VARCHAR), 'NO ENTREGADO') AS ESTADO
FROM PEDIDOS;
--COALESCE
SELECT CodigoPedido, FechaEsperada, FechaEntrega,
COALESCE(FechaEsperada, FECHAENTREGA) AS PRIMERA_FECHA
FROM Pedidos